<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="sort.xsl"?>
<!DOCTYPE sort[
<!ELEMENT sort (element,number, letter)>
<!ELEMENT element (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT letter (#PCDATA)>]>

<sort>
<element>
<number>1</number>
<letter>А</letter>
</element>
<element>
<number>2</number>
<letter>Б</letter>
</element>
<element>
<number>3</number>
<letter>В</letter>
</element>
<element>
<number>4</number>
<letter>Г</letter>
</element>
<element>
<number>5</number>
<letter>Д</letter>
</element>
</sort>