<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<!DOCTYPE info [
<!ELEMENT info (header, text1, text2,text3)>
    <!ELEMENT header (#PCDATA)>
    <!ELEMENT text1 (#PCDATA)>
    <!ELEMENT text2 (#PCDATA)>
    <!ELEMENT text3 (#PCDATA)>
    <!ENTITY header "Что такое XML?">
    <!ENTITY headerTwo "Почему XML важен?">
    <!ENTITY headerThree "В чем преимущества использования XML?">
]>
<info>
<header>&header;</header>
    <text1>
       Расширяемый язык разметки (XML) позволяет определять и хранить данные совместно используемым способом. XML поддерживает обмен информацией между компьютерными системами, такими как веб-сайты, базы данных и сторонние приложения. Предопределенные правила упрощают передачу данных в виде XML-файлов по любой сети, поскольку получатель может использовать эти правила для точного и эффективного чтения данных.
    </text1>
   
    <header>&headerTwo;</header>
    <text2>
        
        Расширяемый язык разметки (XML) – это язык разметки, который предоставляет правила для определения любых данных. В отличие от других языков программирования, XML не может выполнять вычислительные операции сам по себе. Вместо этого для управления структурированными данными можно использовать любой язык программирования или программное обеспечение.

        Например, рассмотрим текстовый документ с комментариями к нему. В комментариях могут содержаться такие предложения:

        Сделайте заголовок жирным
        Это предложение является заголовком
        Это слово автор
        Такие комментарии повышают удобство использования документа, не затрагивая его содержание. Точно так же XML использует символы разметки для предоставления дополнительной информации о любых данных. Другие программы, такие как браузеры и приложения для обработки данных, используют эту информацию для более эффективной обработки структурированных данных.
    </text2>
    <header>&headerThree;</header>
    <text3>
        С помощью XML можно удобно обновлять или изменять дизайн приложения. Многие технологии, особенно новые, имеют встроенную поддержку XML. Они могут автоматически читать и обрабатывать файлы данных XML, чтобы вы могли вносить изменения без необходимости переформатирования всей базы данных.
    </text3>
</info>
